### ISSUE TITLE
Premortems

### ISSUE THREAD

**Issue by wiz** [rodrigosetti/master-plan#6]
The examples currently show The Happy Path. While it's nice already, but it's a [good practice](https://hbr.org/2007/09/performing-a-project-premortem) to define fallbacks.

I'd add a "compiler warning" if sections specified their non-100% trust (is that even realistic, anyway?), but not their failure modes and mitigations.

Hypothetical example:

> I say I will code this project by the week-end. It consists of 3 vital parts: front-end, back-end and documentation.
> I estimate I will complete the front-end with 75% trust using 4h of time. The back-end would take another 2h with success rate of 90%(yay, haskell!). The only thing I dread is documentation, which I expect to finish in 6h with only 30% of confidence.
> Now, the costs are 2+4+6 hours and overall success is 0.75x0.9x0.3... Oops, 20% doesn't look good at all. What can I do to boost this?
> First, what can fail in the front-end? The two things may realistically happen: node_modules would eat all my disk space with 20% chance (for this I will delete my hoard of anime, giving potential cost of 271 movies with 100% certainity. R.I.P) and with another 20%, another framework will come out, stalling my progress by 2h to study it first.

etc. etc. etc

The final tally will show then updated cumulative curves for costs and outcomes.

**Comment by rodrigosetti** [comment]
Pardon if I don't fully understand your idea, but I think you missed the fact that we can model alternatives with sum, and zero-cost hypothesis testing as well without much problem.

Does this model solves your example?

```c
// project.plan
project = frontEnd * backend * documentation;

cost(backend) = 2;
trust(backend) = 90%;

cost(documentation) = 6;
trust(documentation) = 30%;

frontEnd = feImplementation -> (fatNodeModuleIsFine + deleteAnimes) *
                                                     (frameworkIsFine + newFramework);

cost(feImplementation) = 4; // upfront work to implement FE
trust(feImplementation) = 100%;

// It turns out the fat node_modules is not a problem:
cost(fatNodeModuleIsFine) = 0; // the default, but stating explicitly
trust(fatNodeModuleIsFine) = 80%;

cost(deleteAnimes) = 271;  // ... or some quantifiable cost to lose my videos
trust(deleteAnimes) = 100%; // the default, but stating explicitly

// It turns out the framework of choice is modern:
cost(frameworkIsFine) = 0; // the default, but stating explicitly
trust(frameworkIsFine) = 80%;

cost(newFramework) = 2; // learning time
trust(newFramework) = 100%; // the default, but stating explicitly

```

```console
master-plan project.plan -w 1024 -o project.png -r project
```

![example2](https://user-images.githubusercontent.com/99732/29302143-864910ac-8136-11e7-95ad-037e159f2e1f.png)

It's interesting to note a few things:

 * the backup plans have indeed mitigated the initial risk from 20% to 27%
 * the algorithm decided to start from documentation, because it has a high risk and low cost - _i.e._ if might fail on documentation and is cheap to test, so we may do that first to fail fast.
 * the algorithm, naturally, decided to test both whether the fat `node_modules` is fine, and whether the framework is fine, before actually deleting animes or learning a new framework - because both are zero-cost hypothesis testing and the mitigations are zero risk.

**Comment by wiz** [comment]
Thanks. I'll think about it for some more.
